config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get 'courses/index'
  get 'courses/show'
  get 'courses/new'
  get 'courses/edit'

  get 'bookings/thanks_page_booking'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # devise_scope :user do
  #   get '/auth/facebook/callback', to: 'devise/sessions#new'
  #   get '/auth/failure', to: 'devise/sessions#new'
  # end

  resources :courses do
    resources :bookings, only: [:new, :create, :update]
  end


  resources :users, only: [:edit, :update, :show]

  resources :bookings, only: [:show]

  resources :bookings, only: [] do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/user.rb
class User < ApplicationRecord
 # validates :name, presence: true
 # validates :biography, presence: true
 # validates :native_language, presence: true
 # validates :photo, presence: true
 # validates :password, presence: true
 # validates :email, presence: true, uniqueness: true, format: { with: /\A.*@.*\.com\z/ }
 # validates :nationality, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :user_interests
  has_many :user_languages
  has_many :languages, through: :user_languages

  has_many :student_courses, through: :bookings, source: 'Course' # FOR STUDENTS
  has_many :courses
  # FOR TEACHERS
  has_many :bookings
  has_many :teacher_bookings, through: :courses, source: :bookings

  has_many :reviews, through: :bookings # Student review a course
  has_many :interest_tags, through: :user_interests

  has_many :teacher_reviews, through: :courses, source: :reviews
  mount_uploader :photo, PhotoUploader
  validates :name, presence: true, uniqueness: true

  validates :nationality, presence: true, on: :update
  validates :native_language, presence: true, on: :update

  # current_user.teacher_reviews

  def teacher_reviews_for_show
    reviews = []
    courses.each do |course|
      course.bookings.each do |booking|
        if booking.review.present?
        reviews << booking.review
        end
      end
    end
    reviews
  end

  def student?
    courses.empty?
  end

  def teacher?
    !student?
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name # assuming the user model has a name
      user.photo = auth.info.photo # assuming the user model has an image
    end
  end

end

# User.new.student_courses

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def create
  #   if request.env["omniauth.auth"]
  #     user = User.create_with_omniauth(request.env["omniauth.auth"])
  #     session[:user_id] = user.id
  #     redirect_to user_path(user.id)
  #   else
  #     user = User.find_by_email(params[:email])
  #     user && user.authenticate(params[:password])
  #     session[:user_id] = user.id
  #     redirect_to user_path(user.id)
  #   end
  # end

  def edit
    @tags_by_category = InterestCategory.includes(:interest_tags).all.map { |c| [c, c.interest_tags] }.to_h
    @interests = current_user.user_interests
  end

  def update
    create_user_interests
    current_user.update!(user_params)
    redirect_to user_path(current_user)
  end

  def show
    @user = User.find(params[:id])

    @interests = @user.user_interests
    @tags = []
    @interests.each do |interest|
      @tags << interest.interest_tag
    end

    @categories = []
    @tags.each do |tag|
      @categories << tag.interest_category
    end

    @categories = @categories.uniq
    @tags = @tags.uniq

    if @user.student?
      @bookings = @user.bookings
    else
      @courses = @user.courses
      @bookings = @user.teacher_bookings.includes(:course)
    end

    if @user.teacher?
      @reviews_teacher = @user.teacher_reviews_for_show
    end
    @tags_by_category = InterestCategory.includes(:interest_tags).all.map { |c| [c, c.interest_tags] }.to_h

    # @category = current_user.interest_tags.map { |it| it.interest_category }.uniq
  end

  private

  def create_user_interests
    # current_user.user_interests.reject { |ui| ui.interest_tag_id.in? user_params[:interest_tag_ids }.destroy
    interest_tag_ids = user_params[:interest_tag_ids].try(:reject) { |it| it == "" }

    interest_tag_ids.try(:each) do |interest_tag_id|
      UserInterest.create(user_id: current_user.id, interest_tag_id: interest_tag_id)
    end
  end

  def user_params
    params.require(:user).permit(
      :email,
      :name,
      :biography,
      :native_language,
      :photo,
      :nationality,
      :content,
      :rating,
      :teacher_experience,
      interest_tag_ids: []
    )
  end
end

app/views/users/edit.html.erb
<% countries = [
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua And Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegowina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, the Democratic Republic of the",
  "Cook Islands",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard and McDonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic of",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of",
  "Korea, Republic of",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia, The Former Yugoslav Republic Of",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territory, Occupied",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Barthelemy",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe"
] %>


<% spoken_lang = [
"(Afan)/Oromoor/Oriya",
"Abkhazian",
"Afar",
"Afrikaans",
"Albanian",
"Amharic",
"Arabic",
"Armenian",
"Assamese",
"Aymara",
"Azerbaijani",
"Bashkir",
"Basque",
"Bengali/Bangla",
"Bhutani",
"Bihari",
"Bislama",
"Breton",
"Bulgarian",
"Burmese",
"Byelorussian",
"Cambodian",
"Catalan",
"Chinese",
"Corsican",
"Croatian",
"Czech",
"Danish",
"Dutch",
"English",
"Esperanto",
"Estonian",
"Faeroese",
"Fiji",
"Finnish",
"French",
"Frisian",
"Galician",
"Georgian",
"German",
"Greek",
"Greenlandic",
"Guarani",
"Gujarati",
"Hausa",
"Hebrew",
"Hindi",
"Hungarian",
"Icelandic",
"Indonesian",
"Interlingua",
"Interlingue",
"Inupiak",
"Irish",
"Italian",
"Japanese",
"Javanese",
"Kannada",
"Kashmiri",
"Kazakh",
"Kinyarwanda",
"Kirghiz",
"Kirundi",
"Korean",
"Kurdish",
"Laothian",
"Latin",
"Latvian/Lettish",
"Lingala",
"Lithuanian",
"Macedonian",
"Malagasy",
"Malay",
"Malayalam",
"Maltese",
"Maori",
"Marathi",
"Moldavian",
"Mongolian",
"Nauru",
"Nepali",
"Norwegian",
"Occitan",
"Pashto/Pushto",
"Persian",
"Polish",
"Portuguese",
"Punjabi",
"Quechua",
"Rhaeto-Romance",
"Romanian",
"Russian",
"Samoan",
"Sangro",
"Sanskrit",
"Scots/Gaelic",
"Serbian",
"Serbo-Croatian",
"Sesotho",
"Setswana",
"Shona",
"Sindhi",
"Singhalese",
"Siswati",
"Slovak",
"Slovenian",
"Somali",
"Spanish",
"Sundanese",
"Swahili",
"Swedish",
"Tagalog",
"Tajik",
"Tamil",
"Tatar",
"Tegulu",
"Thai",
"Tibetan",
"Tigrinya",
"Tonga",
"Tsonga",
"Turkish",
"Turkmen",
"Twi",
"Ukrainian",
"Urdu",
"Uzbek",
"Vietnamese",
"Volapuk",
"Welsh",
"Wolof",
"Xhosa",
"Yiddish",
"Yoruba",
"Zulu",
] %>

<div class="container">

      <div class="form-post">
        <h1>Complete your profile</h1>
          <%= simple_form_for current_user do |f| %>

            <div>

              <%= f.input :name, input_html: { class:'remove-bootstrap'},
              required: true, label: "Name", class: 'form-control', placeholder: "E.g. Mick Jagger" %>
            </div>
            <div >
              <%= f.input :nationality, collection: countries, input_html: { class:'remove-bootstrap'},
              hint: "leave it blank if you don't want to change it",
              required: true, label: "Country" %>
            </div>
            <div>
              <%= f.input :native_language, input_html: { class:'remove-bootstrap'},
              hint: "leave it blank if you don't want to change it",
              required: true, collection: spoken_lang %>
            </div>
            <% if current_user.teacher? %>
              <div>
                <%= f.input :teacher_experience, input_html: { class:'remove-bootstrap'},
                as: :integer,
                hint: "leave it blank if you don't want to change it",
                required: true,
                label: "Your experience as a teacher" %>
              </div>
            <% end %>
            <div>
              <%= f.input :biography, input_html: { class:'remove-bootstrap'},
              hint: "leave it blank if you don't want to change it",

              required: true, label: "Tell us a little bit about you" %>

            </div>
            <div>
              <%= f.input :photo, input_html: { class:'remove-bootstrap'},
              hint: "leave it blank if you don't want to change it",
              required: true, label: "Upload your profile picture" %>
            </div>
            <br>
            <h1>What of the following tags describe you better</h1>
            <p>Choose 3 per category</p>
            <% @tags_by_category.each do |category, taglist| %>
                <div class="col-xs-12 col-sm-12">
                  <fieldset class="form-group">
                  <input type="hidden" name="user[interest_tag_ids][]" value="">

                  <span><b><%= category.content %></span></b>



                  <div class="category-choices">
                    <% taglist.each do |tag| %>
                      <% if current_user.user_interests.find_by(interest_tag: tag) %>
                        <input class="hidden" hidden type="checkbox" value="<%= tag.id %>" name="user[interest_tag_ids][]" id="user_interest_tag_ids_<%= tag.id %>">
                        <label class="category-choice active" for="user_interest_tag_ids_<%= tag.id %>"><%= tag.content %>
                        </label>
                      <% else %>
                        <input class="hidden" hidden type="checkbox" value="<%= tag.id %>" name="user[interest_tag_ids][]" id="user_interest_tag_ids_<%= tag.id %>">
                        <label class="category-choice" for="user_interest_tag_ids_<%= tag.id %>"><%= tag.content %>
                        </label>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              <% end %>
            <%= f.submit "Save", class: "button-search" %>
          <% end %>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="content-container">

  <!--- profil header --->

  <div class="profil-header">
    <div class="header-infos">
      <h1><%= @user.name %></h1>
      <div class="header-nationality">
        <% if @user.student? %>
          <h4>STUDENT,</h4>
          <h4><%= @user.nationality.try(:upcase)%></h4>
        <% else %>
          <h4>TEACHER,</h4>
          <h4><%= @user.nationality.try(:upcase)%> </h4>
        <% end %>
        <div class="edit-profile">
          <% if current_user.id == params[:id].to_i  %>
            <%= link_to edit_user_path(current_user) do %>
            <i class="far fa-edit"></i>
            <% end %>
          <% end %>
        </div>
      </div>
      <div>
        <% unless @user.teacher_rating.nil? %>
          <% rating = @user.teacher_rating %>
          <% rating.round.times do %>
          <i class="fa fa-star"></i>
        <% end %>
        <% end %>
      </div>
    </div>
    <%= cl_image_tag @user.photo, class: 'avatar-large' %>
  </div>

  <!--- profil description --->

  <div class="profil-description">
    <h2>About me</h2>
    <p><%= @user.biography%></p>
  </div>
  <hr>

  <!--- profil categories --->

  <div class="profil-interests">
    <% @tags_by_category.each do |category, taglist| %>
      <div class="interest-categories">
        <% array = [] %>
        <% category.interest_tags.each do |tag| %>
          <% unless tag.user_interests.where(user_id: @user).empty? %>
            <% array << tag %>
          <% end %>
        <% end %>
        <% unless array.empty? %>
          <h2><%= category.content %></h2>
          <% array = [] %>
        <% end %>

        <% taglist.each do |tag| %>
          <% if @user.user_interests.find_by(interest_tag: tag) %>
            <div class="interest-content">
              <%= tag.content %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <hr>

  <!--- profil languages  --->

  <div class='profil-languages'>
    <h2>Native Language</h2>
    <p><%= @user.native_language%></p>
  </div>

  <hr>

  <!--- profil bookings  --->

  <div class="profil-bookings">
    <% if @user.student? %>
      <h2 style="padding-bottom: 8px;"> Courses & Reviews</h2>
      <% @bookings.each do |booking| %>
      <div class="course-info-student" style="margin-bottom: 12px;">
        <div class="course-booking-review">
          <div class="course-level-user">
            <%= booking.course.level.upcase %><span>, </span>
            <%= booking.course.language.name.upcase %>
            <% if booking.course.language.name == "Spanish" %>
              <%= image_tag('spain-flag.png', :width => 24) %>
            <% else %>
             <%= image_tag('uk-flag.png', :width => 24) %>
            <% end %>
          </div>

          <div class="course-title-user" style="margin-bottom: -4px;">
            <p><%= booking.course.title %></p>
          </div>

          <% if booking.review.nil? %>
            <div class="course-date-review">
              <p>Dates: <%= booking.course.start_date&.strftime("%-d %B").downcase %> - <%= booking.course.end_date&.strftime("%-d %B").downcase %></p>
              <div class="review-comment-2">
                <% if current_user == @user %>
                <%= link_to "Add your review", new_booking_review_path(booking) %>
                <% end %>
              </div>
            </div>
          <% else %>
            <div class="course-date-review">
              <p>Dates: <%= booking.course.start_date&.strftime("%-d %B").downcase %> - <%= booking.course.end_date&.strftime("%-d %B").downcase %></p>
            </div>
            <div class="review-comment-2">
              <i class="far fa-comment"></i> <span> </span> <%= booking.review.try(:content) %>
              <div>
                <% rating = booking.review.try(:rating) %>
                <% if rating %>
                  <% rating.round.times do %>
                  <i class="fa fa-star"></i>
                  <% end  %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <div>
          <%= cl_image_tag booking.course.user.photo, height: 40, width: 40, radius: 50, crop: :fill %>
        </div>
      </div>

      <% end %>
    <%# else  %>
    <%#= render 'reviews/form', booking: booking, review: Review.new %>
    <!-- <p>add review</p> -->
    <%# end %>

    <%# if booking.reviewed? %>
    <%#booking.review.try(:content) %>
    <%# else  %>
    <%#= render 'reviews/form', booking: booking, review: Review.new %>
    <!-- <p>add review</p> -->
    <%# end %>
    <% elsif @user.teacher? %>
      <div class="new-course">
        <h2>Courses</h2>
        <div class="course-review">
          <% if current_user == @user %>
            <%= link_to " + new Course", new_course_path(@user) %>
          <% end %>
        </div>
      </div>
      <% @courses.each do |course| %>
        <div class="courses-reservations">
          <div class="course-info" style="margin-bottom: 12px;">
            <div class="course-level">
              <%= course.language.name.upcase %><span>, </span><%= course.level.upcase %>
            </div>
            <div class="course-title" style="margin-bottom: -4px;">
              <p><%= course.title %></p>
            </div>
            <div class="course-date-review">
              <p><%= course.start_date&.strftime("%-d %B") %> - <%= course.end_date&.strftime("%-d %B")%></p>
            </div>
            <div class="attendees">
              <div class="classmates">
              <% course.bookings.each do |booking| %>
                <% if @user.photo.present? %>
                    <div class="classmate-photo">
                      <%= cl_image_tag booking.user.photo, class: "avatar" %>
                      <div>
                        <p> <%= link_to "#{booking.user.name}", user_path(booking.user.id), :class => "user-profile-links" %></p>
                      </div>
                    </div>
                <% else %>
                  <div class="classmate-photo text-center">
                    <i class="far fa-user fa-2x"></i>
                    <p> <%= booking.user.name %></p>
                  </div>
                <% end %>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>



<!--     <hr style="margin-top: 20px;"> -->
<!--     <h2>My Reservations</h2>
    <%# @bookings.each do |booking| %>
      <div class="course-info" style="margin-bottom: 12px;">
        <div class="course-level">
          <%#= booking.user.name %>
        </div>
        <div class="course-title" style="margin-bottom: -4px;">
          <p><%#= booking.course.title %></p>
        </div>
        <div class="course-date-review">
          <p><%#= booking.course.start_date&.strftime("%-d %B") %> - <%#= booking.course.end_date&.strftime("%-d %B")%></p>
        </div>
      </div>

    <%# else %>
    <p> You have no reservation !</p>
    <%# end %>
  </div>
 -->
  <!--- profil reviews for teacher  --->

  <% if @user.teacher? %>
 <!--  <hr style="margin-top: 50px;"> -->
  <div class="sections-course">
    <div class="teacher-reviews">
      <div id="title-category">
        <h4>Teacher reviews</h4>
      </div>
      <div class="review-info">
          <% if @reviews_teacher.nil? %>
            <p>no review yet</p>
          <% else %>
          <% @reviews_teacher.each do |review|  %>
          <div class="review-detail">
            <% if @user.photo.present? %>
              <div class="">
                <%= cl_image_tag review.try(:booking).try(:user).try(:photo), class: "avatar" %>
              </div>
            <% else %>
              <div class="">
                <i class="far fa-user fa-2x"></i>
              </div>
            <% end %>
            <div class="review-comment">
              <i class="far fa-comment"></i>
                <%= review.try(:content) %>
              <div>
                <% rating = review.try(:rating) %>
                <% if rating %>
                  <% rating.round.times do %>
                  <i class="fa fa-star"></i>
                  <% end  %>
                <% end %>
              </div>
            </div>
<!-- IMPORTANT METHOD TRY: it iterates and if there is an object without content it doesnt raise an error, it moves to the next one -->
          </div>
       <% end %>
        <!-- stars of the review -->
      </div>
      <% end %>
      <div class="all-reviews">
        <p>Read all reviews</p>
      </div>
    </div>
  </div>
  <% end %>
      <%#= link_to "Edit your profile", edit_user_path(current_user) %>

</div>