config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get 'courses/index'
  get 'courses/show'
  get 'courses/new'
  get 'courses/edit'

  get 'bookings/thanks_page_booking'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # devise_scope :user do
  #   get '/auth/facebook/callback', to: 'devise/sessions#new'
  #   get '/auth/failure', to: 'devise/sessions#new'
  # end

  resources :courses do
    resources :bookings, only: [:new, :create, :update]
  end


  resources :users, only: [:edit, :update, :show]

  resources :bookings, only: [:show]

  resources :bookings, only: [] do
    resources :reviews, only: [ :new, :create ]
  end
end

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="content-container">
    <div class="content-title">
      <h1>Be Eloquent. In any language</h1>
      <p>Book group language courses in cool locations & find classmates with common interests</p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand navbar-light navbar-eloquent rounded">
  <div class="content-container" style="display:flex; justify-content: space-between">
   <div class="navbar-logo">
     <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
     <!-- <link href="https://fonts.googleapis.com/css?family=Righteous&display=swap" rel="stylesheet"> -->
     <%= link_to "Eloquent", root_path %>
   </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <% if current_user.photo.present? %>
              <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            <% else %>
            <%= image_tag 'avatar.jpg', height: 40, width: 40, style: "border-radius: 50px", id: "navbarDropdown", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false"  %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <%= link_to "My profile", user_path(current_user)%>
                <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            </div>
            <% end %>
          </li>
          <% else %>
          <div class="login">
            <%= link_to 'Login', new_user_session_path, class: "login-button" %>
          </div>
          <% end %>
      </ul>
    </div>
  </div>
</div>