config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get 'courses/index'
  get 'courses/show'
  get 'courses/new'
  get 'courses/edit'

  get 'bookings/thanks_page_booking'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # devise_scope :user do
  #   get '/auth/facebook/callback', to: 'devise/sessions#new'
  #   get '/auth/failure', to: 'devise/sessions#new'
  # end

  resources :courses do
    resources :bookings, only: [:new, :create, :update]
  end


  resources :users, only: [:edit, :update, :show]

  resources :bookings, only: [:show]

  resources :bookings, only: [] do
    resources :reviews, only: [ :new, :create ]
  end
end

app/views/pages/home.html.erb
<div class="home-container">
<%= render 'shared/banner' %>

<div class="content-container">
  <div class="search-form">
    <%= form_tag(courses_index_path, method: :get) do |f| %>
      <div class="flag">
        <%= text_field_tag :language, params[:language], name: "query[language]", class: 'form-control', placeholder: "Spanish" %>
        <div class="icon-flag">
          <%= icon('far', 'flag') %>
        </div>
      </div>
          <div class="location">
            <%= text_field_tag :city, params[:city], name: "query[city]", class: 'form-control', placeholder: "Barcelona" %>
            <div class="icon-location">
              <%= icon('fas', 'map-marker-alt') %>
            </div>
          </div>
      <%= submit_tag 'Search', class: "button-search" %>
    <% end %>
  </div>
  <div class="become-teacher-div">
    <%= link_to 'Become a Teacher', new_course_path, class: "become-teacher btn button-search"%>
  </div>
</div>
<!-- <div class="">
  <h3 class=""></h3>
</div> -->




<div class="content-container home">
  <div class='how-works'>
    <h3>How to use Eloquent</h3>
  </div>
  <div class="card-how row">
    <div class="card-how-1 col-6">
      <img class="d-block w-100" src="<%= image_path 'how1.jpg' %>"
        alt="First how it works">
    </div>
    <div class="card-how-2 col-6 text-center align">
      <p class="step">STEP 1</p>
      <p>Create an account</p>
    </div>


    <div class="card-how-1 col-6">
      <img class="d-block w-100" src="<%= image_path 'how2.png' %>"
        alt="Second how it works">
    </div>
    <div class="card-how-2 col-6 text-center align">
      <p class="step">STEP 2</p>
      <p>Enter Language & Location</p>
    </div>


      <div class="card-how-1 col-6">
        <img class="d-block w-100" src="<%= image_path 'how3.jpg' %>"
          alt="Second how it works">
      </div>
      <div class="card-how-2 col-6 text-center align">
        <p class="step">STEP 3</p>
        <p>Select your course & teacher</p>
      </div>

      <div class="card-how-1 col-6">
        <img class="d-block w-100" src="<%= image_path 'how4.jpg' %>"
          alt="Second how it works">
      </div>
      <div class="card-how-2 col-6 text-center align">
        <p class="step">STEP 4</p>
        <p> Learn locally with likeminded people</p>
      </div>

      <div class="card-how-1 col-6">
        <img class="d-block w-100" src="<%= image_path 'how5.jpg' %>"
          alt="Second how it works">
      </div>
      <div class="card-how-3 col-6 text-center align">
        <p class="step">STEP 5</p>
        <p> Rate and continue your learning!</p>
      </div>
    </div>
  </div>
</div>